In [2]:
 A = [1,2,3,4]
 C = [[1,5,6,8], A]
 print(type(C))

<class 'list'>


In [3]:
import numpy as np
A1 =np.array(A)
print(A1,type(A1))
C1 = np.array(C)
print("Matrix C1 is \n", C1)

[1 2 3 4] <class 'numpy.ndarray'>
Matrix C1 is 
 [[1 5 6 8]
 [1 2 3 4]]


In [4]:
print(np.shape(A), np.ndim(A))

(4,) 1


In [5]:
print(np.shape(C), np.ndim(C))

(2, 4) 2


In [6]:
X = [1,2,3]
Y = [2,4,6]
Z = [5,10,15]
D1 = [X, Y, Z]
print("D1 is ", D1)
print(np.size(D1))
print(np.ndim(D1))



D1 is  [[1, 2, 3], [2, 4, 6], [5, 10, 15]]
9
2


In [11]:
E1 = [[[[[[X]],[[Y]],[[Z]]]]]]  # OR [[[1, 2, 3]], [[2, 4, 6]], [[5, 10, 15]]]
print(E1)
print(np.ndim(E1))

[[[[[[[1, 2, 3]]], [[[2, 4, 6]]], [[[5, 10, 15]]]]]]]
7
