In [3]:
l1 = [2,5,6,4,8,7]
l2 = [8,56,7,4,2,3]
l3 = [[l1],[l2]]
print(l3)

[[[2, 5, 6, 4, 8, 7]], [[8, 56, 7, 4, 2, 3]]]


In [4]:
print(l3[0])

[[2, 5, 6, 4, 8, 7]]


In [5]:
print(type(l1))
print(type(l3))

<class 'list'>
<class 'list'>


In [6]:
l3 = [[[l1],[l2]]]
print(type(l3))

<class 'list'>


In [7]:
from sympy import pprint
import numpy as np
x1 = np.array(l1)
x2 = np.array(l2)
res = x1*x2
print(res,type(res))

x3 = np.array(['a','z'])
print(x3, type(x3))

[ 16 280  42  16  16  21] <class 'numpy.ndarray'>
['a' 'z'] <class 'numpy.ndarray'>


In [11]:
x = np.array([1,2,3,4,5,7,5,5,7,5])
print(x[2::2])

[3 5 5 7]


In [19]:
#negative slicing
x = np.array([0,1,2,3,4,5,6,7,8,9])
print(x[-3:3:-3])
print(x[-3:3:-2])
print(x[-3:3:-1])

[7 4]
[7 5]
[7 6 5 4]


In [21]:
print(x[-2:10])

[8 9]
