In [3]:
import numpy as np
# import array as arr

#creating an array of numbers
array_1 = np.array([1,2,3,0,5,6,7,0,9,10])

#creating a mask
boolean_mask = (array_1<= 0)

#boolean indexing to filter the numbers less than 0
result = array_1[boolean_mask]

print(boolean_mask, result)

[False False False  True False False False  True False False] [0 0]


In [4]:
import array as array_1
numbers = arr.array('i',[10,20,30,40,50])

print(numbers.index)

NameError: name 'arr' is not defined

In [ ]:
import numpy as np
a = array_1


In [ ]:
a = np.array([[1,2,3],[4,5,6],[2,8,6]])
b = np.array([[9,8,7],[6,5,4],[1,5,4]])

print("Sum = ",np.add(a,b))
print("Substract = ",np.subtract(a,b))
print("Product = ", np.dot(a,b))
print("Product1 = ",a*b)
print("Product2 = ",np.matmul(a,b))
print("Product3 = ", np.cross(a,b))

Sum =  [[10 10 10]
 [10 10 10]
 [ 3 13 10]]
Substract =  [[-8 -6 -4]
 [-2  0  2]
 [ 1  3  2]]
Product =  [[24 33 27]
 [72 87 72]
 [72 86 70]]
Product1 =  [[ 9 16 21]
 [24 25 24]
 [ 2 40 24]]
Product2 =  [[24 33 27]
 [72 87 72]
 [72 86 70]]
Product3 =  [[-10  20 -10]
 [-10  20 -10]
 [  2  -2   2]]


In [ ]:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(f'Original Array:\n{arr1}')
arr1_transpose = arr1.transpose()
print(f'Transposed Array:\n{arr1_transpose}')
# Defining matrices
A = [[1,2],[2,3],[3,4]]
B = [[2,2],[1,1]]
def transpose(mat):
    mat_transpose = [] # initialise transposed matrix
    for idx2 in range(len(mat[0])): # iterate through columns
        new_row = []
    for idx1 in range(len(mat)): # iterate through rows
        new_row.append(mat[idx1][idx2])
        mat_transpose.append(new_row)
    return mat_transpose
print("Original")
print("A =", A)
print("B =", B)
print()
print("Standard Python Transpose")
print("A' =", transpose(A))
print("B' =", transpose(B))
print()
A = np.array(A)
B = np.array(B)
print("NumPy Transpose:")
print("A' =", A.T)
print("B' =", np.transpose(B))
print(" inverse of B =", np.invert(B))

Original Array:
[[1 2 3]
 [4 5 6]]
Transposed Array:
[[1 4]
 [2 5]
 [3 6]]
Original
A = [[1, 2], [2, 3], [3, 4]]
B = [[2, 2], [1, 1]]

Standard Python Transpose
A' = [[2, 3, 4], [2, 3, 4], [2, 3, 4]]
B' = [[2, 1], [2, 1]]

NumPy Transpose:
A' = [[1 2 3]
 [2 3 4]]
B' = [[2 1]
 [2 1]]
 inverse of B = [[-3 -3]
 [-2 -2]]


In [2]:
#Given x,y
#Scaling
# Input the scaling factors
# create a matrix [Sx,0,0,Sy]
# form a column matrix with values x,y
# multiply both we get the final value
#Rotation
# input the angle theta
# create the matrix [cos(theta) ,sin(theta), -sin(theta), cos(theta)]
# form a column matrix with values x,y
# multiply both we get the final value
#Translation
#add the translation factors tx,ty to x and y.

import numpy as np

def scaling(m):
    Sx,Sy = map(int,input("Enter the Scaling factors: ").split())
    mL = [Sx,0,0,Sy]
    Sm = np.array(mL)
    Sm = Sm.reshape(2,2)
    transformed_matrix = np.dot(Sm,m)
    print("The tranformed values are:\nX' = ",transformed_matrix[0,0],"\nY' = ",transformed_matrix[1,0])

def rotation(m):
    theta = int(input("Enter the rotating angle: "))
    mL = [np.cos(theta) ,np.sin(theta), -np.sin(theta), np.cos(theta)]
    Sm = np.array(mL)
    Sm = Sm.reshape(2,2)
    transformed_matrix = np.dot(Sm,m)
    print("The tranformed values are:\nX' = ",round(transformed_matrix[0,0],2), "\nY' = ",round(transformed_matrix[1,0],2))

def translation(m):
    Tx,Ty = map(int,input("Enter the translating factors: ").split())
    mL = [Tx,Ty]
    Sm = np.array(mL)
    Sm = Sm.reshape(2,1)
    transformed_matrix = np.add(Sm,m)
    print("The tranformed values are:\nX' = ",round(transformed_matrix[0,0],2), "\nY' = ",round(transformed_matrix[1,0],2))

x,y = map(int,input("Enter the value of x and y: ").split())
l = [x,y]
m  = np.array(l)
m = m.reshape(2,1)
while True:
    ch = int(input("Enter your choice\n1 for Scaling\n2 for Rotation\n3 for Translation\n4 to Quit."))
    if ch ==1:
        scaling(m)
    elif ch ==2:
        rotation(m)
    elif ch ==3:
        translation(m)
    elif ch ==4:
        break
    else:
        print("Enter a valid choice.")


The tranformed values are:
X' =  25 
Y' =  36
The tranformed values are:
X' =  3.25 
Y' =  7.1
The tranformed values are:
X' =  11 
Y' =  15
